name: develop netcore

on: 
    push:
        branches:
            - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nuget
      run: sudo apt install nuget
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: build with the script
      run: |
        ./ci/build.ps1
      shell: pwsh
    - name: test with the script
      run: |
        ./ci/test.ps1
      shell: pwsh      